### ISSUE TITLE
Menu-Update

### ISSUE THREAD

**Issue by aclai4067** [nss-evening-cohort-10/nutshell-michelin-restaurant#10]
# User Story
As a user, I should be able to edit the menu items
As a user, I should be able to add ingredients to my menu items
As a user, I should be able to remove ingredients to my menu items

# A/C
**when** the user clicks edit next to the description
**then** a modal pops open with a form pre-filled with menu details which they can alter and save
**when** the user clicks edit next to ingredients
**then** a modal pops open with a checkbox list of all ingredients & current ingredients pre-selected

# Dev Notes
* print edit pencil icon next to description with classes `editMenuItemBtn` & `hide`
* print edit pencil icon next to ingredients with classes `editMenuIngredientsBtn` & `hide`
* update auth.js to remove hide from both buttons on authentication & update logout function to add class hide back
* add click listener to `editMenuItemBtn`  that calls `changeMenuItem`
* for `changeMenuItem`:
-- use `$(e.target).closest('.menuCard').attr('id')` to get the menu id 
-- pull object matching menuId from menuItems.json
-- reuse create menu item modal for edit menu details with save button hidden and update button displayed
-- pre-fill form inputs with existing menu details by using ${formItemId}.val(menuItem.key) format
-- add click listener to update button that calls `saveMenuChange`
* for `saveMenuChange`:
-- create updatedMenuItem object filling the keys from menuItems.json with the values of the form inputs [using ${formItemId}.val()]
-- call `updateMenuItem` passing in `updatedMenuItem` object and the menuId
-- .then() call `printMenu` to reprint menu page with new item
* for `updateMenuItem` use axios put method to update `menuItems/${menuId}.json` with `updatedMenuItem` 

* Add click listener to `editMenuIngredientsBtn` that calls `changeMenuIngredients`
* for  `changeMenuIngredients`:
-- use `$(e.target).closest('.menuCard').attr('id')` to get the menu id 
-- hide save button and print update button
-- call `printIngredientsForm`
-- .then() call `menuIngredientsData.getMenuIngredients` and filter results by menuId, save to `currentMenuItem` array
-- loop through currentMenuItem.ingredientId and set to checkboxes with IDs `add-${ingredientId}` to 'checked'
-- add listener to update button to call `saveMenuIngredientChanges` & pass in menuId and currentMenuItem
* for  `saveMenuIngredientChanges`:
-- use forEach & push each currentMenuItem.ingredientId to a new array called`oldIngredients`
-- loop through `.ingredientsListItem` and if checked, split `add-` from the id and push the id to new array called `newIngredients`
-- create two new arrays and use filter method to find ingredients to remove and add
```
const ingredientsToDelete = oldIngredients.filter((x) => !newIngredients.includes(x))
const ingredientsToAdd = newIngredients.filter((x) => !oldIngredients.includes(x))
```
-- call `createMenuIngredients` (from create ticket) & pass in `ingredientsToAdd` and menuId
-- call `deleteMenuIngredients` (from delete ticket) & pass in `ingredientsToDelete`

**Comment by aclai4067** [comment]
use for checkboxes 
```
<h2>rolling toggle</h2>
<input type="checkbox" id="toggle" />
<div>
   <label class="toggleCheck" for="toggle">Name</label>
</div>
```

**Comment by aclai4067** [comment]
array difference methods 
https://medium.com/@alvaro.saburido/set-theory-for-arrays-in-es6-eb2f20a61848

**Comment by zoeames** [comment]
Instead of all these e.target.closest can we use jquery selectors?  $(e.target)...
