### ISSUE TITLE
View a single reservation and all the info

### ISSUE THREAD

**Issue by kelsey-21** [nss-evening-cohort-10/nutshell-michelin-restaurant#100]
# User Story
As a user I should be able to view a single reservation page that displays all the information about that reservation.

# AC
**WHEN** the user clicks on a single reservation
**THEN** the reservation expands
**AND** the other reservations do not display

# Dev Notes
* This should work similarly to pinterest boards and pins
* in `reservations.js`, when a reservation is selected, then all the other reservations are hidden using `addClass('hide')`; and the single reservation should print to a new div in the index with the id `single-reservation`; you will need to add this div
* The user should be able to see additional details about that reservation: including section, staff, menuItems (if applicable) and total bill (if applicable)
* The section collection will contain the staff information; create a smash function called `getStaffAssignedToSection` and display the assigned staff
* if there are menuItems, then display the ordered menuItems and the total Bill

**Comment by kelsey-21** [comment]
![image](https://user-images.githubusercontent.com/54123694/69483424-f14cb300-0dec-11ea-9e27-41967c3c1d40.png)

**Comment by zoeames** [comment]
this page should also show all menu items assigned to the table and a mini bill.   I believe you have another ticket for it but just wanted to point that out since it isn't in this wireframe
