### ISSUE TITLE
top 10 most popular menu item

### ISSUE THREAD

**Issue by djunaim** [nss-evening-cohort-10/nutshell-michelin-restaurant#104]
# Story
As a user I should be able to see a list of the top 10 most popular menu items.

# AC
**WHEN** the user selects the Popularity radio button on the Reporting page
**THEN** the appropriate dropdown is printed for Popularity
**AND** the dropdown options are "least popular" and "most popular"
**AND** when most popular is selected
**THEN** the 10 most popular items are displayed below

# Dev Notes
* make sure the user authentication within the `navbar.js` file inside the `logoutEvent` function for the `Reporting` button so it shows when the user is logged in, but does not when the user is logged out exists; if not add it
* create a div with id `popular-items` 
* within `menu.js` file, create function called `popularItems` by using `menuData.js` to get `quantitySold` 
* within `menuData.js` create a function that sorts the menuItems by quantitySold largest to smallest
* create a radio button for the menu section, the radio options are Ingredients, Revenue and Popularity
* create a drop down menu to list out the different options `most popular items` and `least popular items` and have a `save` button at the end; this dropdown menu only appears if Popularity is selected
* create an event listener for the `save` button to listen for the `id` of the most or least popular and when the radio button is `checked` it will print the 10 most popularItems 
* use `printToDom` to print out the menu items and qty used that since the beginning of time in table as a bootstrap chart

**Comment by kelsey-21** [comment]
https://getbootstrap.com/docs/4.3/content/tables/

**Comment by kelsey-21** [comment]
![image](https://user-images.githubusercontent.com/54123694/69483769-0a576300-0df1-11ea-9ef9-34c750e7971f.png)

**Comment by kelsey-21** [comment]
![image](https://user-images.githubusercontent.com/54123694/69483782-3b379800-0df1-11ea-8491-a5732079d978.png)
