### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by gseals** [nss-evening-cohort-10/nutshell-michelin-restaurant#19]
# User Story

As a developer, when I open this, I would like to see an ERD of how our data will interact

# AC

**WHEN** I open this ticket
**THEN** I should see screenshots of an ERD

# Dev Notes

* Use [Lucid Chart](https://www.lucidchart.com/) to create an ERD
* paste them into this ticket

**Comment by gseals** [comment]
![image](https://user-images.githubusercontent.com/52087296/68815963-92e04180-0642-11ea-8055-7a40e38668ec.png)

**Comment by aclai4067** [comment]
remove isAvailable from menuItems
