### ISSUE TITLE
WireFrame/Mockup

### ISSUE THREAD

**Issue by aclai4067** [nss-evening-cohort-10/nutshell-michelin-restaurant#28]
# User Story
As a developer, I would like to see a mockup of the expected site display

# A/C
**When** I open this ticket
**Then** I will see the mockup

# Dev Notes
- Use [https://app.moqups.com/](https://app.moqups.com/) to create a set of wireframes for each of the different modules.
- Once wireframes are created include in the comments below along with any tickets associated with the specific module.

**Comment by aclai4067** [comment]
logged out home:
![image](https://user-images.githubusercontent.com/47763728/68822211-f162eb00-0655-11ea-9e4e-ec42eddd1617.png)

**Comment by aclai4067** [comment]
logged in home:

![image](https://user-images.githubusercontent.com/47763728/68822243-0c355f80-0656-11ea-85bd-b64fe00fff8d.png)

**Comment by aclai4067** [comment]
menu:  
![image](https://user-images.githubusercontent.com/47763728/68822271-1ce5d580-0656-11ea-8d80-e90e476b50e4.png)

**Comment by aclai4067** [comment]
staff:  
![image](https://user-images.githubusercontent.com/47763728/68822314-3555f000-0656-11ea-89f3-e501126feb24.png)

**Comment by aclai4067** [comment]
reservations:
![image](https://user-images.githubusercontent.com/47763728/68823237-c75ef800-0658-11ea-8e25-200ef5347edb.png)

**Comment by aclai4067** [comment]
ingredients:

![image](https://user-images.githubusercontent.com/47763728/68824036-2de51580-065b-11ea-93af-12a2cdef6e09.png)

**Comment by broach44** [comment]
Seating Chart:

![image](https://user-images.githubusercontent.com/51486216/68963258-24af9200-079c-11ea-939e-a46e3c301be7.png)
