### ISSUE TITLE
Ingredients-Read

### ISSUE THREAD

**Issue by broach44** [nss-evening-cohort-10/nutshell-michelin-restaurant#29]
# User Story
As a user, I would like to navigate to the Inventory module and see the ingredients for the entire restaurant.
# AC
**WHEN** I navigate to the inventory module
**THEN** I should see a collection of ingredients
 # Dev Notes
- Create a new file at the following directory  `src/javascripts/helpers/data/inventoryData.js`
- Be sure to import axios and the apikeys
- Create a new promise called "getInventory" that will return an array of objects from the ingredients collection.  It should look something like this:
```javascript
const getInventory = () => new Promise((resolve, reject) => {
  axios.get(`$baseUrl}/ingredients.json`)
    .then((response) => {
      const demIngredients = response.data;
      const ingredients = [];
      Object.keys(demIngredients).forEach((fbId) => {
        demIngredients[fbId].id = fbId;
        ingredients.push(demIngredients[fbId]);
    });
    resolve(ingredients);
  })
  .catch((error) => reject(error));
});
```
- Export the "getInventory" function
- Create a new javascript component at the following location `src/javascripts/inventory/inventory.js` 
- Create a Sass file called `inventory.scss` in this same directory
- Import this Sass file into the newly created component
- Import the "getInventory" function created in the inventoryData.js file into the inventory.js file
- Create a function called "printIngredients" with a forEach loop that will loop over the data returned by the promise and print this data to a div with an id of "inventoryDiv" that is contained within the div with an id of "loggedInDiv"
- Using Sass the component should look like the wireframe included in the comments below.
- Export the "printIngredients" function
- Import "printIngredients" function to the init function in the main.js

**Comment by broach44** [comment]
![image](https://user-images.githubusercontent.com/51486216/68903280-44917800-0700-11ea-8921-2c1954875a12.png)

**Comment by broach44** [comment]
Once the user home is created we will likely need to move the call of this function and others into one component so they are called when the user clicks on the various links in the secondary navigation.

**Comment by zoeames** [comment]
This is super minor and more of a stretch goal BUT users are stupid so have you thought about a way to prevent users from adding an ingredient that already exists?

**Comment by broach44** [comment]
Should be easy enough to add in...had not thought of that yet...
