### ISSUE TITLE
Create Base File for Seed Data/firebase setup

### ISSUE THREAD

**Issue by broach44** [nss-evening-cohort-10/nutshell-michelin-restaurant#31]
# User Story
As a developer, I am going to need some seed data to work with, before I can upload  the data I will need a structure setup in firebase

# AC
**WHEN** I navigate to firebase console
**THEN** I should see the base file giving structure for the data

# Dev Notes
- set firebase project to a web type app
- enable google signin
- create javascripts>helpers and add two files: apiKeys.json and apiKeysExample.json
- add apiKeys to gitignore
- store your API keys in apiKeys.json & an empty template in apiKeysExample.json
- import firebase and apiKeys into main.js and add firebase.initializeApp(apiKeys.firebaseKeys); to init()
- Create a db directory at the root of the project
- Create a file called base.json
- Enter the following items as keys in the object:  menuItems, menuItemIngredient, seating, reservations, ingredients, staff
- For each of the keys enter some "dummy" data to hold the places
- Upload to the firebase console database created for this project

**Comment by zoeames** [comment]
Make all of your collections end in a s - its a sanity thing

Your base should look like this:
```
{
  “menuItems” : “gato tacos”, 
  “menuItemIngredients”: “dogs”, 
  “seatings”:  “table”, 
  “reservations”: “many”, 
  “ingredients”: “cats”, 
  “staffs”: “Greg”
}
```
