### ISSUE TITLE
Create Seating Seed Data

### ISSUE THREAD

**Issue by broach44** [nss-evening-cohort-10/nutshell-michelin-restaurant#33]
# User Story
As a developer, I will need some sample data to print and test on the page.
# AC
**WHEN** I look into firebase console for the project
**THEN** I should see a collection of tables
# Dev Notes
- Create a file called seating.json and place in a directory called `db` at the root of the project
- Enter in information for 20-24 tables for the restaurant seating.  The information should contain the following keys:  id and numOfSeats.  Use the reference below as a guide to enter data.

```
{
  "table1": {
      "numOfSeats": "  ",
  },
  "table2": {
      "numOfSeats": " ",
  },
  "table3": {
      "numOfSeats": " ",
  }
}
```
- Once the data is created upload into the firebase console at the appropriate link for seating for this project.

**Comment by zoeames** [comment]
These should have a name too right?

**Comment by broach44** [comment]
We had scrapped the name because we felt it was redundant and would be the same name as the id for the table and would be unlikely for a major change in floor plan naming.  So example: table1, table2, etc.  If you feel it is better to have the name and the id we can easily change.
