### ISSUE TITLE
If ingredients sold out, can't assign menu item to reservation

### ISSUE THREAD

**Issue by djunaim** [nss-evening-cohort-10/nutshell-michelin-restaurant#92]
# Story
As a user I should not be able to assign a menu item to a reservation if any of the ingredients from that menu item are sold out.

# AC 
**WHEN** The place order button is clicked
**THEN** The order modal pops up with a pre-populated list of available menu-items
**AND** If an ingredient is out of stock then the menu item is disabled.

# Dev Notes
* `$('button').on('click', '#placeOrder', checkAvailable)`
* `checkAvailable()` filters through `ingredients` and checks `amountStocked`.
* Filter `menuItemIngredients` for all menu items containing all ingredients where`amountStocked` === 0
* forEach `menuItem` addClass `disabled`

**Comment by zoeames** [comment]
be careful with this one.  the way you have it written performance will be slow.  get it working and we can optimize it after
