### ISSUE TITLE
Total revenue since restaurant opening

### ISSUE THREAD

**Issue by djunaim** [nss-evening-cohort-10/nutshell-michelin-restaurant#95]
# Story
As a user I want to be able to see what the total revenue is for my restaurant since I opened.

# AC
**WHEN** I navigate to the `reporting` page, select the radio button for `revenue` and `year to date` in the dropdown
**THEN** I should see a report of all ytd revenue

# Dev Notes
* This will  be a `smash` function
* Use `orders.json` to collect all used `menuItemId`.
* `forEach` `order`, `.push` `menuItemId` to an `[]`.
* Then use all `menuItemId` within `[]`, to pull `menuItems.price` and `+=` the prices into a YTD total. 
* use `printToDom` to print it to the page.

**Comment by zoeames** [comment]
use a reduce method for this - much less code
