### ISSUE TITLE
Assign table to reservation

### ISSUE THREAD

**Issue by kelsey-21** [nss-evening-cohort-10/nutshell-michelin-restaurant#96]
# User Story
As a user I should be able to assign a table in the seating collection to a reservation.

# AC
**WHEN** I make a reservation
**THEN** I should be able to use a drop down menu to assign a table to that reservation

# Dev Notes
* Change create/edit reservation `modal` table selection field to a dropdown menu that is populated with available table numbers.
* Get available table numbers from `seatings.json` and use `printToDom` to print the available tables into the modal in the div labeled `inlineFormCustomSelect` in the example below (change id as necessary).
* Once a table is selected and the reservation made, the reservation is either created or updated using `axios`.

**Comment by LaCollins** [comment]
Bootstrap form eg.

```
<form>
  <div class="form-row align-items-center">
    <div class="col-auto my-1">
      <label class="mr-sm-2" for="inlineFormCustomSelect">Preference</label>
      <select class="custom-select mr-sm-2" id="inlineFormCustomSelect">
        <option selected>Choose...</option>
        <option value="1">One</option>
        <option value="2">Two</option>
        <option value="3">Three</option>
      </select>
    </div>
</form>
```

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/69483677-e5162500-0def-11ea-9d30-5870b8addf9c.png)
